-- SQL Script to import Stage 1 results (optimized)
-- This version uses a single INSERT with VALUES and subqueries
-- The rider_id is looked up from the riders table using first_name and last_name

-- First, verify that Stage 1 exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM stages WHERE stage_number = 1) THEN
    RAISE EXCEPTION 'Stage 1 does not exist. Please run import-stages-2025.sql first.';
  END IF;
END $$;

-- Insert Stage 1 results using VALUES with JOIN to look up rider_id
-- Using DISTINCT ON to handle cases where multiple riders have the same name
INSERT INTO stage_results (stage_id, rider_id, position, time_seconds, same_time_group)
SELECT DISTINCT ON (v.first_name, v.last_name, v.position)
  s.id as stage_id,
  r.id as rider_id,
  v.position,
  v.time_seconds,
  v.same_time_group
FROM (VALUES
  ('Jasper', 'Philipsen', 1, 13991, 1),
  ('Biniam', 'Girmay', 2, NULL, 1),
  ('Soeren', 'Waerenskjold', 3, NULL, 1),
  ('Anthony', 'Turgis', 4, NULL, 1),
  ('Matteo', 'Trentin', 5, NULL, 1),
  ('Clement', 'Russo', 6, NULL, 1),
  ('Paul', 'Penhoet', 7, NULL, 1),
  ('Matteo', 'Jorgenson', 8, NULL, 1),
  ('Marius', 'Mayrhofer', 9, NULL, 1),
  ('Samuel', 'Watson', 10, NULL, 1),
  ('Mike', 'Teunissen', 11, NULL, 1),
  ('Ivan', 'Cortina', 12, NULL, 1),
  ('Niklas', 'Maerkl', 13, NULL, 1),
  ('Harry', 'Sweeny', 14, NULL, 1),
  ('Krists', 'Neilands', 15, NULL, 1),
  ('Kevin', 'Vauquelin', 16, NULL, 1),
  ('Damien', 'Touze', 17, NULL, 1),
  ('Tadej', 'Pogacar', 18, NULL, 1),
  ('Pascal', 'Ackermann', 19, NULL, 1),
  ('Jonas', 'Vingegaard', 20, NULL, 1),
  ('Jasper', 'Stuyven', 21, NULL, 1),
  ('Marco', 'Haller', 22, NULL, 1),
  ('Kaden', 'Groves', 23, NULL, 1),
  ('Kasper', 'Asgreen', 24, NULL, 1),
  ('Peter', 'Joseph Blackmore', 25, NULL, 1),
  ('Luka', 'Mezgec', 26, NULL, 1),
  ('Tiesj', 'Benoot', 27, NULL, 1),
  ('Mathieu', 'van der Poel', 28, NULL, 1),
  ('Stian', 'Fredheim', 29, NULL, 1),
  ('Tobias', 'Johannessen', 30, NULL, 1),
  ('Enric', 'Mas', 31, NULL, 1),
  ('Tim', 'Wellens', 32, NULL, 1),
  ('Cyril', 'Barthe', 33, NULL, 1),
  ('Jonas', 'Abrahamson', 34, NULL, 2),
  ('Jonas', 'Rickaert', 35, NULL, 2),
  ('Xandro', 'Merlier', 36, NULL, 2),
  ('Davide', 'Ballerini', 37, NULL, 2),
  ('Edoardo', 'Affini', 38, NULL, 2),
  ('Jonathan', 'Milan', 39, NULL, 2),
  ('Arnaud', 'de Lie', 40, NULL, 2),
  ('Bryan', 'Coquard', 41, NULL, 2),
  ('Jordi', 'Meeus', 42, NULL, 2),
  ('Pavel', 'Bittner', 43, NULL, 2),
  ('Alberto', 'Dainese', 44, NULL, 2),
  ('Robert', 'Stannard', 45, NULL, 2),
  ('Phil', 'Bauhaus', 46, NULL, 2),
  ('Tim', 'Merlier', 47, NULL, 2),
  ('Wout', 'van Aert', 48, NULL, 2),
  ('Danny', 'van Poppel', 49, NULL, 2),
  ('Neilson', 'Powless', 50, NULL, 2),
  ('Markus', 'Hoelgaard', 51, NULL, 2),
  ('Clement', 'Berthet', 52, NULL, 2),
  ('Tobias', 'Lund Andresen', 53, NULL, 2),
  ('Mattias', 'Skjelmose', 54, NULL, 2),
  ('Jasper', 'De Buyst', 55, NULL, 2),
  ('Emanuel', 'Buchmann', 56, NULL, 2),
  ('Guillaume', 'Boivin', 57, NULL, 2),
  ('Joao', 'Almeida', 58, NULL, 2),
  ('Amaury', 'Capiot', 59, NULL, 2),
  ('Dylan', 'Groenewegen', 60, NULL, 2),
  ('Magnus', 'Cort', 61, NULL, 2),
  ('Arnaud', 'Demare', 62, NULL, 2),
  ('Alexis', 'Renard', 63, NULL, 2),
  ('Ben', 'Healy', 64, NULL, 2),
  ('Matis', 'Louvel', 65, NULL, 2),
  ('Aurelian', 'Paret-Peintre', 66, NULL, 2),
  ('Remco', 'Evenepoel', 67, NULL, 2),
  ('Jordan', 'Jegat', 68, NULL, 2),
  ('Carlos', 'Rodriguez', 69, NULL, 2),
  ('Gianni', 'Vermeersch', 70, NULL, 2),
  ('Santiago', 'Buitrago', 71, NULL, 2),
  ('Michael', 'Valgren', 72, NULL, 2),
  ('Oliver', 'Naesen', 73, NULL, 2),
  ('Oscar', 'Onley', 74, NULL, 2),
  ('Felix', 'Gall', 75, NULL, 2),
  ('Ilan', 'Van Wilder', 76, NULL, 2),
  ('Pascal', 'Eenkhoorn', 77, NULL, 2),
  ('Florian', 'Lipowitz', 78, NULL, 2),
  ('Primož', 'Roglic', 79, NULL, 2),
  ('Lennert', 'van Eetvelt', 80, NULL, 2),
  ('Valentin', 'Madouas', 81, NULL, 2),
  ('Guillaume', 'Martin', 82, NULL, 2),
  ('Nelson', 'Oliveira', 83, NULL, 2),
  ('Fabian', 'Lienhard', 84, NULL, 2),
  ('Sean', 'Flynn', 85, NULL, 2),
  ('Connor', 'Swift', 86, NULL, 2),
  ('Geraint', 'Thomas', 87, NULL, 2),
  ('Thomas', 'Gachignard', 88, NULL, 2),
  ('Jhonatan', 'Narvaez', 89, NULL, 2),
  ('Hugo', 'Page', 90, NULL, 2),
  ('Staff', 'Cras', 91, NULL, 2),
  ('Bastion', 'Tronchon', 92, NULL, 2),
  ('Alexandre', 'Delettre', 93, NULL, 2),
  ('Jack', 'Haig', 94, NULL, 2),
  ('Alex', 'Aranburu', 95, NULL, 2),
  ('Marc', 'Hirschi', 96, NULL, 2),
  ('Jenno', 'Berckmoes', 97, NULL, 2),
  ('Dylan', 'Teuns', 98, NULL, 2),
  ('Brent', 'van Moer', 99, NULL, 2),
  ('Tobias', 'Foss', 100, NULL, 2),
  ('Fred', 'Wright', 101, NULL, 2),
  ('Jarrad', 'Drizners', 102, NULL, 2),
  ('Vincenzo', 'Albanese', 103, NULL, 2),
  ('Elmar', 'Reinders', 104, NULL, 3),
  ('Aleksandr', 'Vlasov', 105, NULL, 3),
  ('Callum', 'Scotson', 106, NULL, 3),
  ('Warren', 'Barguil', 107, NULL, 3),
  ('Matej', 'Mohoric', 108, NULL, 3),
  ('Alex', 'Baudin', 109, NULL, 3),
  ('Clement', 'Venturini', 110, NULL, 3),
  ('Bert', 'van Lerberghe', 111, NULL, 3),
  ('Toms', 'Skujins', 112, NULL, 3),
  ('Edward', 'Theuns', 113, NULL, 3),
  ('Vito', 'Braet', 114, NULL, 3),
  ('Laurence', 'Pithie', 115, NULL, 3),
  ('Simone', 'Consonni', 116, NULL, 3),
  ('Mattia', 'Cattaneo', 117, NULL, 3),
  ('Victor', 'Campenaerts', 118, NULL, 3),
  ('Sepp', 'Kuss', 119, NULL, 2),
  ('Gianni', 'Moscon', 120, NULL, 4),
  ('Mick', 'van Dijke', 121, NULL, 4),
  ('Ion', 'Izagirre', 122, NULL, 4),
  ('Marc', 'Soler', 123, NULL, 4),
  ('Kamil', 'Gradek', 124, NULL, 4),
  ('Nils', 'Politt', 125, NULL, 7),
  ('Andreas', 'Leknessund', 126, NULL, 7),
  ('Anders', 'Johannessen', 127, NULL, 7),
  ('Quentin', 'Pacher', 128, NULL, 7),
  ('Harold', 'Tejada', 129, NULL, 7),
  ('Bruno', 'Armirail', 130, NULL, 7),
  ('Sebastian', 'Grignard', 131, NULL, 7),
  ('Mathis', 'le Berre', 132, NULL, 7),
  ('Thymen', 'Arensman', 133, NULL, 7),
  ('Jonas', 'Rutsch', 134, NULL, 7),
  ('Eduardo', 'Sepulveda', 135, NULL, 7),
  ('Georg', 'Zimmermann', 136, NULL, 7),
  ('Gregor', 'Muehlberger', 137, NULL, 7),
  ('Benjamin', 'Thomas', 138, NULL, 7),
  ('Einar', 'Rubio', 139, NULL, 7),
  ('Cristian', 'Rodriguez', 140, NULL, 7),
  ('Frank', 'van den Brook', 141, NULL, 7),
  ('Quinn', 'Simmons', 142, NULL, 7),
  ('Tim', 'Naberman', 143, NULL, 7),
  ('Sergio', 'Higuita', 144, NULL, 7),
  ('Clement', 'Champoussin', 145, NULL, 7),
  ('Laurenz', 'Rex', 146, NULL, 7),
  ('Pablo', 'Castrillo', 147, NULL, 7),
  ('Raul', 'Garcia', 148, NULL, 7),
  ('Romain', 'Gregoire', 149, NULL, 7),
  ('Ewen', 'Costiou', 150, NULL, 7),
  ('Valentin', 'Paret-Peintre', 151, NULL, 7),
  ('Emilien', 'Jeanniere', 152, NULL, 7),
  ('Michael', 'Storer', 153, NULL, 7),
  ('Edward', 'Dunbar', 154, NULL, 7),
  ('Pavel', 'Sivakov', 155, NULL, 7),
  ('Adam', 'Yates', 156, NULL, 7),
  ('Emiel', 'Verstrynge', 157, NULL, 7),
  ('Jake', 'Stewart', 158, NULL, 7),
  ('Alexey', 'Lutsenko', 159, NULL, 7),
  ('Ben', 'O''Connor', 160, NULL, 1),
  ('Mauro', 'Schmid', 161, NULL, 7),
  ('Marijn', 'Van den Berg', 162, NULL, 1),
  ('Luke', 'Durbridge', 163, NULL, 8),
  ('Simon', 'Yates', 164, NULL, 8),
  ('Axel', 'Laurance', 165, NULL, 8),
  ('Silvan', 'Dillier', 166, NULL, 8),
  ('Michael', 'Woods', 167, NULL, 8),
  ('Simone', 'Velasco', 168, NULL, 8),
  ('Maximilian', 'Schachmann', 169, NULL, 8),
  ('Lucas', 'Plapp', 170, NULL, 8),
  ('Yevgeniy', 'Fedorov', 171, NULL, 8),
  ('Cees', 'Bol', 172, NULL, 8),
  ('Julian', 'Alaphilippe', 173, NULL, 8),
  ('Roel', 'Van Sintmaartensdijk', 174, NULL, 8),
  ('Louis', 'Barre', 175, NULL, 8),
  ('Ivan', 'Romeo', 176, NULL, 8),
  ('William', 'Barta', 177, NULL, 8),
  ('Mathieu', 'Burgaudeau', 178, NULL, 8),
  ('Matteo', 'Vercher', 179, NULL, 8),
  ('Thibau', 'Nys', 180, NULL, 8),
  ('Lewis', 'Askey', 181, NULL, 8),
  ('Lenny', 'Martinez', 182, NULL, 11)
) AS v(first_name, last_name, position, time_seconds, same_time_group)
INNER JOIN stages s ON s.stage_number = 1
INNER JOIN riders r ON r.first_name = v.first_name AND r.last_name = v.last_name
ORDER BY v.first_name, v.last_name, v.position, r.id
ON CONFLICT (stage_id, rider_id) DO UPDATE SET
  position = EXCLUDED.position,
  time_seconds = EXCLUDED.time_seconds,
  same_time_group = EXCLUDED.same_time_group;

-- Verify the import
SELECT
  s.stage_number,
  s.name as stage_name,
  COUNT(sr.id) as result_count,
  MIN(sr.position) as best_position,
  MAX(sr.position) as worst_position
FROM stages s
LEFT JOIN stage_results sr ON s.id = sr.stage_id
WHERE s.stage_number = 1
GROUP BY s.id, s.stage_number, s.name;

-- Show top 20 results for Stage 1
SELECT
  sr.position,
  r.first_name || ' ' || r.last_name as rider_name,
  tp.name as team_name,
  sr.time_seconds,
  sr.same_time_group
FROM stage_results sr
INNER JOIN stages s ON sr.stage_id = s.id
INNER JOIN riders r ON sr.rider_id = r.id
LEFT JOIN teams_pro tp ON r.team_pro_id = tp.id
WHERE s.stage_number = 1
ORDER BY sr.position
LIMIT 20;