-- SQL Script template to update rider photos with base64 data
-- This script will be populated by the Python script or manually
-- Format: UPDATE riders SET photo_url = 'data:image/jpeg;base64,...' WHERE id = X;

-- Example structure (replace with actual base64 data):
-- UPDATE riders SET photo_url = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD...' WHERE id = 1 AND first_name = 'Tadej' AND last_name = 'Pogačar';

-- Note: This file will be generated by the Python script
-- Or you can manually add UPDATE statements here with base64 data

-- To use this script:
-- 1. Run the Python script (download-rider-photos.py) to automatically fetch and process photos
-- 2. Or manually add UPDATE statements below with base64 encoded images

-- Example for one rider:
-- UPDATE riders 
-- SET photo_url = 'data:image/jpeg;base64,YOUR_BASE64_DATA_HERE' 
-- WHERE id = 1;

